### ISSUE TITLE
Query not working with SolrCloud in standalone mode

### ISSUE THREAD

**Issue by fsantagostinobietti** [inoio/solrs#11]
When running SolrCloud in standalone mode 
```shell
$ bin/solr start -cloud -e cloud
```
 I get following error as result of every query: 
```
WARN solrs.AsyncSolrClient: Query failed for server SolrServer(http://127.0.1.1:7574/solr/gettingstarted_shard1_replica2/, Enabled), not retrying. Exception was: io.ino.solrs.RemoteSolrException: Expected mime type [] but got [text/html].
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/gettingstarted_shard1_replica2//select. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

io.ino.solrs.RemoteSolrException: Expected mime type [] but got [text/html].
...
```
As you can see in query url there is a double '/' before 'select':  /solr/gettingstarted_shard1_replica2//select .
In embedded mode Solr runs (by default) on Jetty and the double slash in the url gets it confused.
On the contrary if you deploy Solr webapp on Tomcat error disappears.

**Comment by magro** [comment]
Thanks for reporting this! I just released 1.3.4 with a fix for this, should be available in maven central during the next hour.
