### ISSUE TITLE
RoundRobinLB not load balancing in update request with CloudSolrServers 

### ISSUE THREAD

**Issue by dordor12** [inoio/solrs#116]
RoundRobinLB not load balancing in update request with CloudSolrServers. Due it's ShardReplica.findLeader method that return only first leader in all cluster servers.

 In my opinion update request should be equally distributed across cluster leaders as regular query request.

**Comment by almogtavor** [comment]
I agree. Maybe there should be an option for users to configure it with a parameter in this method (should load balance or not)

**Comment by bensilvan** [comment]
I also faced that issue, Its very confusing that a client that configured as round robin always takes the first leader when adding docs

**Comment by magro** [comment]
Would anybody like to submit a PR for this?

**Comment by magro** [comment]
I just submitted PR #152 to address this issue here. Would be nice to get some feedback if this would solve the issue for you @dordor12, @bensilvan, @almogtavor.

**Comment by magro** [comment]
The change integrated with #152 is now released with 2.9.0, closing this issue here.
