### ISSUE TITLE
Using query.process(client, collection) in Java

### ISSUE THREAD

**Issue by almogtavor** [inoio/solrs#150]
Hey
I'd like to use 

```java
final DirectJsonQueryRequest query = new DirectJsonQueryRequest()..setQuery("""
{
  "query" : "name:iPod"
}
""");
final QueryResponse response = query.process(solrClient, COLLECTION_NAME);
````

I wonder how to do this in `solrs`. I've found the `execute` method and more methods that may seem relevant, but they require `SolrResponseFactory`. I haven't found any Java way of passing a query object as a parameter to a method that will be equivalent to `process`. Is there such method already?

**Comment by almogtavor** [comment]
@MarcoPriebe I'd really appreciate your opinion here

**Comment by almogtavor** [comment]
@MarcoPriebe I'd really appreciate your opinion here

**Comment by magro** [comment]
Hi @almogtavor, in #151 I just added an test that shows how to execute a `DirectJsonQueryRequest`. Does that answer your question?

**Comment by almogtavor** [comment]
@magro Thank you! That really helped. I understand now that the main reason I didn't got it at first was that I wasn't aware for how to use `SolrResponseFactory`. I think this shall be added to the docs (I can do it myself if you want). Anyway thanks a lot

**Comment by magro** [comment]
A PR to improve docs would be awesome, @almogtavor!
