### ISSUE TITLE
Allow multiple instances of FastestServerLB globally

### ISSUE THREAD

**Issue by cavallium** [inoio/solrs#178]
Currently, in Solrs 3, when you build a FastestServerLB instance, it will call initJmx().

Calling initJmx() twice will cause an exception, because it will try to register the class MBean twice, so you can't create two instances of FastestServerLB globally.

**Comment by magro** [comment]
The latest version is 2.11.0, therefore I'd release the fix as solrs 2.11.1.

**Comment by magro** [comment]
The fix is released with version 2.11.1 now.
