### ISSUE TITLE
Query method POST, double sending all params 

### ISSUE THREAD

**Issue by gilnoh** [inoio/solrs#25]
While testing SolrS to replace SolrJ, I've found a bug. 
When the query method is selected as POST, all parameters passed to Solr (q, fq, ... or any manually set parameters) are duplicated. This is one such log output from Solr server. 

`2017-05-30 07:19:25.544 INFO  (qtp472654579-12) [   x:question] o.a.s.c.S.Request [question]  webapp=/solr path=/select params={q=frage&q=frage&fq=answers.isEmpty:false&fq=answers.expirationDate:[NOW+TO+*]&fq=answers.startDate:[*+TO+NOW]&fq=answers.visibility:(PUBLIC)&fq=language:DE&fq=tenant.id:1&fq=answers.isEmpty:false&fq=answers.expirationDate:[NOW+TO+*]&fq=answers.startDate:[*+TO+NOW]&fq=answers.visibility:(PUBLIC)&fq=language:DE&fq=tenant.id:1&wt=javabin&wt=javabin&version=2&version=2} hits=2 status=0 QTime=8
`

Naturally on SolrJ, using POST does not make this type of parameter duplication. 
I have not traced the code to check why this occurs, but first thing that hits my mind is that the arguments are maybe passed twice -- once on URL header (just like GET case), and once more on the POST body .... 

Note that, duplications are normally not very visible, unless ... 
- Query repeated twice, and can make different score.  
-- On a server with http header size limited, this can make different ranks (e.g. part of query duplicated and gets more score, part lost are only on POST part) 
- Special params such as MoreLikeThis query's body.stream --- server exception occurs if they detect duplicated param.

**Comment by magro** [comment]
Thanks for reporting! Unfortunately currently I'm quite loaded and cannot look into it. If you want to further analyze this this would be great!

**Comment by gilnoh** [comment]
Got it. Will trace the issue and try to produce a patch / pull request.

**Comment by magro** [comment]
Awesome!
