### ISSUE TITLE
Shard Support

### ISSUE THREAD

**Issue by souravtyson** [inoio/solrs#41]
Please provide a shard support as it is very important feature of solr, in performance issue, while dealing with huge amount of data.

**Comment by magro** [comment]
Using shards should basically be possible, there's just no optimized request routing implemented.

What exactly are you looking for?

**Comment by magro** [comment]
The statement in the readme is too general, it refers to optimized request routing / load balancing based on shard information.

I suggest you use it and try if it fits your needs. If you're missing something please reach out (there's also a gitter channel).
