### ISSUE TITLE
Enable 'raw' queries by overriding default responseparser per request 

### ISSUE THREAD

**Issue by mahlingam** [inoio/solrs#50]
I am looking forward to integrate official solrs releases again hopefully in the near future. Since I had to support existing frameworks relying on XML and JSON responses, solrs official QueryResponse was not an option. In order to still use solrs clustering capabilities, I had to find a way to get arbitrary response formats from solrs. Please see PR https://github.com/inoio/solrs/pull/49
I am aware, that there is an alternative solution available: creating new client instances for every response format. The reason for not going with that, was the additional IO caused by every new client instance for keeping the cluster state up-to-date.

**Comment by magro** [comment]
Closed with #49 

I just released solrs 2.2.0 - it's currently on its way to maven central...

**Comment by mahlingam** [comment]
awesome.
