### ISSUE TITLE
DefaultAsyncHttpClient throwing java.lang.NumberFormatException error with Play framework

### ISSUE THREAD

**Issue by phraniiac** [inoio/solrs#51]
I have a play scala app in which I am trying to use solrs.

1. Scala version - **"2.12.3"**
2. Play WS AHC version - **"com.typesafe.play" %% "play-ahc-ws" % "2.6.9"**
3. Solrs version - **"io.ino" %% "solrs" % "2.1.0"**

Build.sbt dependencies

```sbt
  "com.google.inject" % "guice" % "4.1.0",
  "com.typesafe.akka" %% "akka-http" % "10.0.5",
  "ch.qos.logback" % "logback-classic" % "1.1.7",
  "com.typesafe.scala-logging" %% "scala-logging" % "3.5.0",
  "org.mongodb" %% "casbah" % "3.1.1",
  "com.github.salat" %% "salat" % "1.11.2",
  "com.typesafe.play" %% "play-ws" % "2.7.0-M1",
  "com.typesafe.play" %% "play-json" % "2.6.8",
  "com.google.guava" % "guava" % "21.0",
  "com.typesafe.play" %% "play-ahc-ws" % "2.7.0-M1",
  "org.spire-math" %% "spire" % "0.13.0",
  "io.ino" %% "solrs" % "2.1.0"
```

Usage - 

```scala
  import io.ino.solrs._
  import io.ino.solrs.future.ScalaFutureFactory.Implicit
  val servers = new CloudSolrServers(uri)
  val asyncHttpClient = new DefaultAsyncHttpClient()
  val solrClient = new MoolSolrClient(AsyncSolrClient.Builder(RoundRobinLB(servers))
      .withHttpClient(asyncHttpClient).build)
```

I have tried the workarounds specified here, but it still gives me the same error specified below - 

[https://github.com/playframework/play-ws/issues/87](https://github.com/playframework/play-ws/issues/87)

```
Caused by: java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.asynchttpclient.config.AsyncHttpClientConfigHelper$Config.getInt(AsyncHttpClientConfigHelper.java:109)
	at org.asynchttpclient.config.AsyncHttpClientConfigDefaults.defaultHttpClientCodecInitialBufferSize(AsyncHttpClientConfigDefaults.java:240)
	at org.asynchttpclient.DefaultAsyncHttpClientConfig$Builder.<init>(DefaultAsyncHttpClientConfig.java:712)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:69)
	at org.asynchttpclient.Dsl.asyncHttpClient(Dsl.java:28)
```

Is there a workaround, like if only through simple modifications, solrs could support Play version of DefaultAsyncHtpClient(as play uses the same library internally)?

**Comment by magro** [comment]
Shouldn't this be fixed with https://github.com/playframework/play-ws/pull/149?

AFAICS newer versions of AHC (2.4.5+) come with a solution (https://github.com/AsyncHttpClient/async-http-client/pull/1538), so play-ws should just update to this one. 

If things described/suggested in the play-ws issue don't work for you, you should discuss this there (maybe in their chat).

In general, the issue tracker should be used to report issues of the library (here this would be solrs), for questions / asking for help the chat is a better channel.
