### ISSUE TITLE
Is there a best practice to use APIs

### ISSUE THREAD

**Issue by nnanda2016** [inoio/solrs#54]
What's the best practice to use `JavaAsyncSolrClient`? I am planning to use it in my web app; so I want to know if it's thread safe or not. Currently we use SolrJ's `CloudSolrClient` which is thread-safe and we share a singleton instance of this for all incoming requests. Can we do same for `JavaAsyncSolrClient`?

**Comment by magro** [comment]
As answered in [gitter](https://gitter.im/inoio/solrs?at=5b7fb0d03815912505664f59) it's thread safe.
