### ISSUE TITLE
CloudSolrClient

### ISSUE THREAD

**Issue by AceHack** [inoio/solrs#66]
How do I get the same feature as the following from CloudSolrClient?

    /**
     * Tells {@link Builder} that created clients should send direct updates to shard leaders only.
     *
     * UpdateRequests whose leaders cannot be found will "fail fast" on the client side with a {@link SolrException}
     */
    public Builder sendDirectUpdatesToShardLeadersOnly() {
      directUpdatesToLeadersOnly = true;
      return this;
    }

    /**
     * Tells {@link Builder} that created clients can send updates to any shard replica (shard leaders and non-leaders).
     *
     * Shard leaders are still preferred, but the created clients will fallback to using other replicas if a leader
     * cannot be found.
     */
    public Builder sendDirectUpdatesToAnyShardReplica() {
      directUpdatesToLeadersOnly = false;
      return this;
    }

**Comment by magro** [comment]
This is the behavior of solrs 2.2+, it got added with #45.

See also [this blog post](https://inoio.de/blog/2018/07/29/solrs-2.2.0-released/) telling a bit more about that.

Is that what you were asking for?
