### ISSUE TITLE
RoundRobinLB idx is not thread safe

### ISSUE THREAD

**Issue by billyean** [inoio/solrs#68]
We're using RoundRobinLB in a hight parallelized application, we found out our solr cloud were hit on unbalanced requests. We found RoundRobinLB class is using a local idx.(is that possible to change it to AtomicInteger here)

`  private var idx = 0`

=>

`private final val idx = new AtomicInteger(0)`
`val next = idx.incrementAndGet()`
`Success(preferred(next % preferred.length))`

**Comment by magro** [comment]
Hi @billyean, sounds good! Do you want to submit a PR for this?

**Comment by billyean** [comment]
Submiited a PR https://github.com/inoio/solrs/pull/69, somehow travis is picking up JDK9, not able to fix it
