### ISSUE TITLE
Throughput lower than expected  

### ISSUE THREAD

**Issue by fsantagostinobietti** [inoio/solrs#8]
In my test environment I've tested **Solrs client** for maximum throughput (requests per second).
I got that my upper bound is nearly 1600 req/s. 
As a comparison I ran plain **Solrj client** in the same scenario and I got 1500 req/s. Good.
Now comes the strange part of the story (at least for me).
In my tests, when I load balance requests against multiple instances of Solrj (running in the same JVM) throughput rises - for ex. with 3 solrj instances I get up to 3000 req/s.
On the contrary using multiple instances of Solrs client does not give any performance boost: total throughput is always up to 1600 req/s.

Are there some Solrs configurations I can try to increase throughput ?

**Comment by magro** [comment]
Can you share the code for the benchmark, or at least the construction of the AsyncSolrClient instances?
What I'd really like is to have a self contained benchmark that we could analyze/improve together! :-)

**Comment by fsantagostinobietti** [comment]
This is the base code I use to do my simple tests: 

https://gist.github.com/fsantagostinobietti/a51dbd8304f6f5db042d#file-solrs_benckmark-java

It's in Java since I'm quite new to Scala and code base in which I need to use solrs is mainly Java. :)

**Comment by magro** [comment]
Thanks! I didn't go though all of it, but AFAICS you're using only a single instance of AsyncSolrClient, and not multiple instances as I'd have expected according to your description. So how exactly are you testing with multiple instances? And how does the test for solrj look like?

I'd try to introduce a common interface for solrs and solrj, so that the same test can be run with both and differences from the test cannot influence the results. Because solrj has a sync interface, you need to make it async - you can just use Future.successful for this.

Regarding solrs throughput, because this should depend on the underlying AsyncHttpClient, you could to use a custom AHC and play with its configuration. You can pass a configured AHC to solrs like this:

```java
AsyncHttpClient ahc = new AsyncHttpClient(new AsyncHttpClientConfig.Builder().build());
new AsyncSolrClient.Builder(new RoundRobinLB(servers)).withHttpClient(ahc).build();
```

Out of interest: why are you using java for the test? Would you use solrs with java as well?

**Comment by fsantagostinobietti** [comment]
You are right, I posted only the single instance version of the code. This is the version with multiple solrs clients : 

https://gist.github.com/fsantagostinobietti/80b485f5130330b2e0b9#file-solrs_multiple_clients_benchmark-java

this is the same as previous one, the only difference is that an array of solrs clients is created and then each virtual user has one client assigned to (in round robin way). 
Another test done, simpler then this, was to run at the same time 3 instances of the first benchmark code (the single instance one). So I had  3 distinct JVMs each running the test. 
Again the same result : total throughput does not change.

Thanks for your suggestion about AsyncHttpClient configuration. I'll try it and let you know if I succeed. :-)

PS. In my company code is written mainly in Java. For this reason I want to try solrs with Java, at first.

**Comment by magro** [comment]
How does the test with solrj look like? I'd still favor using the same benchmark code for both clients, otherwise it's hard to compare things...

Re Java: perhaps it makes sense to create a java friendly api and provide this as an alternative...?

**Comment by magro** [comment]
What I already find suspicuous is [this Await](https://gist.github.com/fsantagostinobietti/80b485f5130330b2e0b9#file-solrs_multiple_clients_benchmark-java-L200) - it's always dangerous! ;-)

**Comment by fsantagostinobietti** [comment]
ok, I will write a unique benchmark for both solrj/solrs clients. So it will be easier for results comparison.

In my tests each virtual user send a request and than waits for the response, then sends a new request, etc. Load is increased by increasing the number of virtual users.
This is done easily with solrj since it has sync api. Whereas in solrs I had to use the Await command.
Do you think it can generate performance issues? What could I use instead?

PS. Java api for Solrs? I like it :+1:  :D

**Comment by magro** [comment]
Using solrs makes sense if you can make use of its async api, i.e. you are using some web framework that can handle async responses (like e.g. [play framework](https://playframework.com/documentation/2.4.x/JavaAsync)). If your app is running in a synchronous/blocking context (you must return the result directly, not wrapped in a Future) I don't see that much value in using solrs, and I'd recommend to use solrj. Or what's your motivation to use solrs?

What's the environment (web framework, sync/async) in your case?
What are your throughput requirements?

Regarding the number of virtual users: typically there would not be one solr client instance per user, but only a single instance. A user request is typically represented by a thread, which then accesses the solr client.
To simulate multiple users, I'd say that a ExecutorService of a fixed size N could be used, so that for at max N users queries are simulated.

PS. would you like to submit a PR for a java api, as a basis for discussion? :-)

**Comment by magro** [comment]
@fsantagostinobietti I've created a gist that allows to compare solrj/solrs using the same code.

Implementation notes:
- starts an embedded solr server
- only a single instance of solrj/solrs is used, the number of concurrent queries can be changed (to simulate concurrent users)
- solrj.query is wrapped with a Future (`Future.successful`, so that no additional thread is created)

Usage:
- in the solrs project copy to `src/test/scala/io/ino/solrs/Benchmark.scala`
- add `connectInput in (Test,run) := true` to build.sbt
- run `sbt`
- in sbt start the benchmark with `test:runMain io.ino.solrs.Benchmark 4 solrj` to simulate 4 concurrent users with solrj, use "solrs" instead of "solrj" to test solrs

On my laptop (4 cores with hyperthreading) with 8 concurrent requests I got 8833 req/sec for solrs and 4783 req/sec for solrj (both running for ~30 seconds).

https://gist.github.com/magro/42c32863178bc9cbc126

**Comment by fsantagostinobietti** [comment]
Thanks for sharing your benchmark code. 
I'm trying to compile it, but I have following errors : 

```
object SolrUtils is not a member of package io.ino.solrs
[error] import io.ino.solrs.SolrUtils._
not found: value SolrRunner
[error]   val solrRunner = SolrRunner.startOnce(8888)
...
```

Am I missing something?

Anyway, I will have to change it a little bit since I need to connect to SolrCloud cluster (it is part of my CDH - Cloudera distribution).
This is my scenario. I need to expose REST APIs for querying CDH cluster. I want the REST service to be completely asynchronous when making requests to back-end (solr and hbase).
REST front-end is a Jboss Wildfly instance configured for handling requests asynchronously. Hbase is accessed with [asynchbase library](https://github.com/OpenTSDB/asynchbase) and Solr is queried with your Solrs lib.
Business logic to compose data from hbase and solr is implemented with Akka.
Everything is working fine, but at high throughput rates solrs becomes a bottleneck. That's why I started benchmarking solrs and solrj.

My requirement is to get at least 4000 req/s. With solrs for me max rate was 1600 req/s.
Currently I've replaced solrs with solrj+Future (to make it async), but this cost me a lot of threads. It's not a scalable solution :( 
I'm looking for a better solution with solrs, which I think is the right library for the job.

**Comment by magro** [comment]
> object SolrUtils is not a member of package io.ino.solrs
It seems as if you've placed Benchmark.scala under src/main/scala, this must be src/test/scala...

> Hbase is accessed with asynchbase library and Solr is queried with your Solrs lib. Business logic to compose data from hbase and solr is implemented with Akka.
Thanks for sharing this, then infact you can benefit from async libs.

> Everything is working fine, but at high throughput rates solrs becomes a bottleneck.
Are you sure that solrs is the bottleneck and not the solr server? Do you have a real life example that shows how solrs is setup and used, and how it's becoming a bottleneck?

**Comment by magro** [comment]
@fsantagostinobietti I just updated the gist to use solrcloud: https://gist.github.com/magro/42c32863178bc9cbc126 - this should then be easily changed to use your existing cluster.

**Comment by fsantagostinobietti** [comment]
Yes, Benchmark.scala was under src/main/scala. Sorry, my fault :(
Now it builds and runs. I'm going to test solrcloud benchmark in my cluster.

Talking about a possible bottleneck: I excluded Solr server since using (multiple instances of) solrj client I get more than 3000 req/s. Thus the server is able to handle all of them.
I still think it can be a misconfiguration/misuse of solrs in my project. For this reason using your Benchmark in my cluster is a precious test. I'll post results asap ...

**Comment by magro** [comment]
You can also share code that shows how you're using it (in akka?) so that I can have a look.

**Comment by fsantagostinobietti** [comment]
Here are the results of your benchmark code running connected to my Solr cluster.
 
#virtual users | solrs (req/s) | solrj (req/s) | solrj w/ 3 instances (req/s)
------------------|-----------------|----------------|---------------------------------
5     | 831   | 801   | 2206
10   | 1570 | 1260 | 3342
20   | **2105** | 1228 | 3271
40   | 1437 | 1248 | 3235
100 | **1641** | 1237 | 3302

Solrs client has max throughput (2100 req/s) with 20 virtual users. With more users asymptotically reach 1600 req/s value. 

Solrj client has a different behaviour: quickly gets its max throughput (1250 req/s); which is lower than solrs one.

Last test for me is the most important. I ran (on the same host) 3 concurrent solrj benchmark. Throughput is computed summing up each single benchmark throughput. In this scenario max value is 3300 req/s.

These results confirm my previous tests. I have the feeling that solrs could have an higher throughput, but for some reason it cannot. I've no clue about it at the moment. 

What do you think of these results ?

**Comment by magro** [comment]
Before thinking further about this: can you do the same for solrs, run 3 concurrent solrs benchmarks?

**Comment by magro** [comment]
And can you please test using the embedded solrcloud (solrrunner), so that we can compare our numbers? 
How many cpu cores do you have btw?

**Comment by fsantagostinobietti** [comment]
I've updated results table with a new column (solrs with 3 instances)
 
#virtual users | solrs (req/s) | solrs w/ 3 instances (req/s) | solrj (req/s) | solrj w/ 3 instances (req/s)
------------------|-----------------|----------------------------------|-----------------|-----------------
5     | 831   | 2166 | 801   | 2206
10   | 1570 | 1439 | 1260 | 3342
20   | **2105** | 1542 | 1228 | 3271
40   | 1437 | 1693 | 1248 | 3235
100 | **1641** | **1838** | 1237 | 3302

A clarification about tests with multiple instances: #virtual users is the number of users for each instance. So the total number of users is 3x for tests with 3 instances.

**Comment by fsantagostinobietti** [comment]
I ran the embedded tests with the same configuration as yours  : 

```
> Running io.ino.solrs.Benchmark 8 solrs
Success rate: 15344 req/sec

> Running io.ino.solrs.Benchmark 8 solrj
Success rate: 4558 req/sec
```

My PC has 8 virtual CPUs running on 4 cores.

**Comment by magro** [comment]
Ok, so you have a rather good throughput on localhost, probably this is cpu bound - you should see a nearly maxed out cpu usage.

Changing to remote solr this is dropping significantly, for both solrj and solrs, but much more for solrs. This seems to be i/o bound. 
The main difference between solrj and solrs is blocking io vs non-blocking io.

Therefore I'd look into this layer, e.g. try to use another provider for async-http-client (AHC) than netty, or change the netty configuration. 

Are you running linux? Then I'd be interested in the output of 'vmstat 1' while the test is running.
If you're running Windows I'd be interested how a test on linux looks like.

**Comment by magro** [comment]
Which jvm are you running? Can you use a current jvm if this is not yet the case?

**Comment by magro** [comment]
AFAICS it's possible to activate blocking io for netty: https://github.com/AsyncHttpClient/async-http-client/blob/1.8.x/src/main/java/com/ning/http/client/providers/netty/NettyAsyncHttpProvider.java#L242

Can you try that as well?

**Comment by fsantagostinobietti** [comment]
I'm running all my tests on Linux with JVM 1.8 (Java HotSpot 64-Bit Server).

https://gist.github.com/fsantagostinobietti/61d464b85dbe60338b1c#file-benchmark-vmstat
Here is the output file of 'vmstat 1' command used when running this benchmark on my cluster : 
```
  Starting with solrs SolrS, running 100 queries in parallel
  ...
  Success rate: 1614 req/sec
```

I made another test which surprises me a little bit. 
It makes no difference if I run concurrent benchmarks on the same machine or on different machines. The total throughput I can get is always the same (and values are exactly those in my last table). 
These machines share nothing, they only access the same external solr cluster. Somehow they interfere each other when "talking" with solr servers.

A question about solrs:  your documentation says that current version does not support shard for SolrCloud. What does it mean? Could this affect performances?

**Comment by magro** [comment]
Re vmstat: I don't see more from this what might be the issue - your system is more or less idle.

Re shard support: I think I mentioned this because the `_route_` parameter is not taken into account, see also [Advanced Distributed Request Options](https://cwiki.apache.org/confluence/display/solr/Advanced+Distributed+Request+Options). But this cannot be an issue regarding throughput, I'd also assume that you're not using this.

Re throughput is the same from different machines: Is there some traffic shaping going on, or some firewall limiting i/o? Can you run the benchmark on one of the solr machines or from some machine within the same lan?

**Comment by fsantagostinobietti** [comment]
Maybe now I have a clue on what's going on.
I've made a tcpdump for both solrs and solrj benchmarks. In those dumps I can see that solrj opens a connection for each solr server in the cluster, whereas solrs connects only to 2 severs (don't know how they are chosen). 
Our cluster has 18 servers and 9 shards. So in this scenario solrj has much more open connections in which it can send requests.

Hope this info could help. I would like to do some more tests (and the one you suggested me), but tomorrow I will be on vacation for a bit of time :boat: :palm_tree: ;-)

**Comment by magro** [comment]
Great that you've found it, now I'll have to check solrs. Can you share the solrcloud setup with servers, collections, shards and replicas? The output of CLUSTERSTATUS should tell everything I need. 

Vacation sounds great, mine will start next week :-)

**Comment by fsantagostinobietti** [comment]
This is the content of clusterstate.json file from SolrCloud admin : 
https://gist.github.com/fsantagostinobietti/a584739b5b776c073122#file-cluster_status-json
(I was not able to use the CLUSTERSTATUS action command, but I think info are the same)

**Comment by magro** [comment]
Thanks, that's what I need.

**Comment by magro** [comment]
@fsantagostinobietti I just pushed 1.3.3, now all servers from all shards and replicas should be used.

**Comment by fsantagostinobietti** [comment]
Back from vacation I was very anxious to test 1.3.3 ...  
Below updated comparison table solrs/solrj :

#virtual users | solrs 1.3.3 (req/s) | solrs 1.3.2 (req/s) | solrj (req/s)
------------------|-----------------|----------------|---------------------------------
5     | 842  | 831   | 801   
10   | 1617 | 1570 | 1260 
20   | 3159 | 2105 | 1228 
40   | **5793** | 1437 | 1248
100 | **11681** | 1641 | 1237 

I'm very satisfied of resulting throughput :+1: ! Great work!
Thanks a lot.

**Comment by magro** [comment]
Great, so I'm closing this.

Just another question: we talked about a java api and I'm still thinking about it. Do you have any expectations for this that should be taken into account? Which kind of future would you prefer to get back from `query`, scala future, guava ListenableFuture or java8 CompletableFuture?

**Comment by fsantagostinobietti** [comment]
I found it was quite easy to use solrs from Java. 
Scala future is ok (now I'm working with java7), but probably with java8 CompletableFuture will be the best option.
I had just one problem with default values during class CloudSolrServers instantiation. My code was something like this (a bit ugly) :
```java
Duration zkClientTimeout = CloudSolrServers.$lessinit$greater$default$2();	// default value 2nd parameter
Duration zkConnectTimeout = CloudSolrServers.$lessinit$greater$default$3();	// default value 3rd parameter
Duration clusterStateUpdateInterval = CloudSolrServers.$lessinit$greater$default$4();	// default value 4th parameter
Option<String> defaultCollection = Option.apply(null); // None value
Option<WarmupQueries> warmupQueries = Option.apply(null); // None value
		
CloudSolrServers servers = new CloudSolrServers( 
			zkQuorum, 
			zkClientTimeout, 
			zkConnectTimeout, 
			clusterStateUpdateInterval, 
			defaultCollection, 
			warmupQueries  );
```

Java-friendly constructors could be enough for me.

**Comment by magro** [comment]
Ok, thanks, I created issue #10 to track this.
