### ISSUE TITLE
Support for solr8.8.2

### ISSUE THREAD

**Issue by billyean** [inoio/solrs#82]
Can we test if it supports latest solr 8.8.2 and 8.9 version since there are some security vulnerabilities found in 8.6

**Comment by magro** [comment]
Hi @billyean, do you want to submit a PR?

**Comment by billyean** [comment]
I created PR as https://github.com/inoio/solrs/pull/83

There are still 2 test failures but I don't see it's related to the upgrade of solar version.

**Comment by billyean** [comment]
Can we get update on these?

**Comment by billyean** [comment]
Appreciate if we can get update on this

**Comment by magro** [comment]
As said in #83 already, I just released solrs 2.6.0 built with solr 8.11.1 (see also #84). I'm closing the issue here already, if that doesn't work for you please reopen.
